# Default pull policy for images
image:
  pullPolicy: IfNotPresent

# Network Monitoring Config
monitor:
  image:
    repository: alpine/k8s # Alpine-based image with kubectl
    tag: "1.28.3"
  checkIntervalSeconds: 15
  heartbeatIp: "54.175.180.74" # Gateway instance
  nodeLabelKey: "myapp.com/network-status"
  # Optional: nodeSelector if needed later
  # nodeSelector: {}